#!/bin/bash
#simple script for git automation 

echo
echo
echo "   ***   git   ***"

echo "1) git push"
echo "2) git pull"
read something		#reads user input 


if [ "$something" = "1" ]; then
	echo "its push (might need login/passwd) (might need login/passwd)"
	git push origin master
	
elif [ "$something" = "2" ]; then
	echo "its pull"
	git pull origin master
else 
	echo "wrong choice !!"
fi

echo "  --> end of script <-- "

